plugins:
  - stylelint-order
  - stylelint-scss

extends:
  - stylelint-config-standard
  - stylelint-config-sass-guidelines
  - stylelint-config-prettier

rules:
  no-descending-specificity: ~
  color-named: ~
  selector-max-id: ~
  selector-no-qualifying-type: ~
